### ISSUE TITLE
Compatibility with Bun

### ISSUE THREAD

**Issue by jo-project** [AllMightySauron/ascii-table3#15]
I try to use ascii-table3 using Bun but I got this error
```
ENOTDIR: Not a directory
   path: "/home/joproject0911/Code/typescript/local/unnamed-bot/node_modules/ascii-table3/src/ascii-table3.js/../ascii-table3.styles.json"
 syscall: "open"
   errno: -20

      at new AsciiTable3 (/home/joproject0911/Code/typescript/local/unnamed-bot/node_modules/ascii-table3/src/ascii-table3.js:42:33)
      at /home/joproject0911/Code/typescript/local/unnamed-bot/src/services/event.ts:15:24
      at _initialize (/home/joproject0911/Code/typescript/local/unnamed-bot/src/services/event.ts:12:24)
      at /home/joproject0911/Code/typescript/local/unnamed-bot/src/struct/client.ts:37:12
      at registerListeners (/home/joproject0911/Code/typescript/local/unnamed-bot/src/struct/client.ts:35:52)
      at /home/joproject0911/Code/typescript/local/unnamed-bot/src/struct/client.ts:31:18
      at /home/joproject0911/Code/typescript/local/unnamed-bot/src/struct/client.ts:30:37
      at processTicksAndRejections (:1:2602)
```

**Comment by AllMightySauron** [comment]
fixed in [0.9.0](https://github.com/AllMightySauron/ascii-table3/releases/tag/0.9.0)
